spring:
  application:
    name: threadpool
server:
  port: 8081

nacos:
  config:
    server-addr: 127.0.0.1:8848
    type: yaml
    data-ids: threadpool-nacos.yml
    auto-refresh: true
    group: DEFAULT_GROUP
    bootstrap:
      enable: true
      log-enable: true
logging:
  level:
    com:
      alibaba:
        nacos: debug
  #config: classpath:logback-dev.xml
